### ISSUE TITLE
Import Error: No module named argparse

### ISSUE THREAD

**Issue by RhozzDev** [willroberts/minecraft-tools#1]
Hello, i try to use "python rcon_shell.py --host 127.0.0.1 --port 25765" as example, but i get this error:

Traceback (most recent call last):
  File "rcon_shell.py", line 2, in <module>
    from  argparse import ArgumentParser
ImportError: No module named argparse.

any idea how to solve this ? thx

**Comment by willroberts** [comment]
Hi,

Which operating system and Python version are you using? The `argparse` module is built into Python 2.7 and 3.x -- it sounds like you may be on 2.6 or an earlier version.

You may be able to solve this by running `sudo pip install argparse` (or look into using `virtualenv` to manage your Python packages).

**Comment by RhozzDev** [comment]
Hello, thanks for reply, well..
I am running windows 7 & have Python 2.6, i have installed pip and argparse, after i have used "python setup.py install" and after "python setup.py build", after, i tried to use "python test.py" but i get this error:

"rcon.py:150: DeprecationWarning: catching of string exceptions is deprecated, except(error) as ret_val: False"

**Comment by RhozzDev** [comment]
Hi, 
I am running Windows 7 and Python 2.6, i have installed argparse and the rcon works perfectly!
thank you so much!
